INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (1, 1, 181, NULL, 2); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (2, 1, 182, NULL, 3); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (3, 1, 346, NULL, 6); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (4, 1, 347, NULL, 5); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (5, 1, 1069, NULL, 1); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (6, 1, 1102, NULL, 4); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (7, 2, 181, NULL, 2); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (8, 2, 182, NULL, 3); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (9, 2, 293, NULL, 4); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (10, 2, 301, NULL, 5); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (11, 2, 995, NULL, 6); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (12, 2, 1069, NULL, 1); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (13, 3, 182, NULL, 2); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (14, 3, 405, NULL, 3); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (15, 3, 407, NULL, 4); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (16, 3, 1069, NULL, 1); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (17, 4, 186, NULL, 2); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (18, 4, 192, NULL, 4); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (19, 4, 210, NULL, 3); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (20, 4, 1069, NULL, 1); GO
INSERT INTO [Rep_Definicion_Campos] ([Id], [DefinicionId], [CampoCatalogoId], [AliasPersonalizado], [Orden]) VALUES (21, 4, 1108, NULL, 5); GO
